#!/bin/bash
set -eo pipefail

startProjector() {
    local idePattern=${1}
    sudo apt-get install -qq --no-install-recommends \
        libfreetype6 \
        libxext6 \
        libxi6 \
        libxrender1 \
        libxtst6 \
        python3-dev  \
        python3-pip

    # Install from GitHub to fix: https://github.com/JetBrains/projector-installer/pull/8
    cd $(mktemp -d)
    git clone https://github.com/JetBrains/projector-installer.git .
    pip3 install --quiet --user -r requirements.txt
    python3 setup.py bundle
    pip3 install --quiet --user .
    cd -
    # Prevent projector from prompting to agree to a license
    # https://github.com/JetBrains/projector-installer/blob/ee878ddee0795a910b9913d62fbb305f6985247c/projector_installer/cmd.py#L25
    mkdir -p ~/.projector/configs
    tmux new -d -s projector ~/.local/bin/projector ide install --no-auto-run "${idePattern}"
}

sudo usermod --shell /bin/bash ${USER}
sudo apt-get install -y libyaml-dev

startProjector 'RubyMine 2020.3.2'
alias mine='/home/spin/.projector/configs/RubyMine/run.sh'
ln -sf ~/dotfiles/.bash_profile ~/.bash_profile
